"""Editorial guard matrix (doc 17 `POST /content/{id}/transition`, doc 00 §4). Pure function, no DB."""
from __future__ import annotations

import itertools

import pytest

from app.content.transitions import (
    ALL_STATUSES,
    allowed_targets,
    can_transition,
    is_editable,
    is_known_transition,
)
from app.models.enums import ContentStatus, MemberRole

ROLES = ["owner", "admin", "editor", "approver", "viewer"]


@pytest.mark.parametrize("role,expected", [("owner", True), ("admin", True), ("editor", True), ("approver", True),
                                           ("viewer", False)])
def test_submit_for_review(role: str, expected: bool):
    assert can_transition(role, "draft", "needs_review") is expected
    assert can_transition(role, "ai_generated", "needs_review") is expected


@pytest.mark.parametrize("role,expected", [("owner", True), ("admin", True), ("approver", True), ("editor", False),
                                           ("viewer", False)])
def test_approve_and_reject_require_approver(role: str, expected: bool):
    assert can_transition(role, "needs_review", "approved") is expected
    assert can_transition(role, "needs_review", "rejected") is expected


@pytest.mark.parametrize("role", ROLES)
def test_archive_is_admin_only_from_any_status(role: str):
    for frm in ALL_STATUSES:
        expected = role in ("owner", "admin") and frm != "archived"
        assert can_transition(role, frm, "archived") is expected, (role, frm)


def test_back_to_draft_paths():
    assert can_transition("editor", "approved", "draft")
    assert can_transition("editor", "rejected", "draft")
    assert can_transition("editor", "needs_review", "draft")
    assert not can_transition("viewer", "approved", "draft")
    assert can_transition("admin", "archived", "draft") and not can_transition("editor", "archived", "draft")


def test_no_shortcuts_to_approved():
    for role, frm in itertools.product(ROLES, ALL_STATUSES):
        if frm != "needs_review":
            assert not can_transition(role, frm, "approved"), (role, frm)
    # nobody can move content *into* ai_generated by hand (only the AI pipeline does)
    for role, frm in itertools.product(ROLES, ALL_STATUSES):
        assert not can_transition(role, frm, "ai_generated")


def test_same_status_and_unknown_values():
    assert not can_transition("owner", "draft", "draft")
    assert not can_transition("owner", "draft", "published")
    assert not can_transition("superuser", "draft", "needs_review")
    assert not is_known_transition("draft", "approved")
    assert is_known_transition("needs_review", "approved")
    assert is_known_transition("approved", "archived")


def test_accepts_enums():
    assert can_transition(MemberRole.approver, ContentStatus.needs_review, ContentStatus.approved)
    assert not can_transition(MemberRole.editor, ContentStatus.needs_review, ContentStatus.approved)


def test_allowed_targets_and_editability():
    assert set(allowed_targets("editor", "draft")) == {"needs_review"}
    assert set(allowed_targets("owner", "needs_review")) == {"approved", "rejected", "draft", "archived"}
    assert is_editable("draft") and is_editable("ai_generated") and not is_editable("approved")
    assert not is_editable("archived")
