from typing import Protocol


class StorageProvider(Protocol):
    async def put(self, bucket: str, key: str, data: bytes, content_type: str) -> None: ...
    async def get(self, bucket: str, key: str) -> bytes: ...
    async def delete(self, bucket: str, key: str) -> None: ...
    async def presign_put(self, bucket: str, key: str, content_type: str, expires_s: int = 900) -> str: ...
    async def presign_get(self, bucket: str, key: str, expires_s: int = 900) -> str: ...
    def public_url(self, bucket: str, key: str) -> str | None: ...
